# Generated by Django 4.1 on 2022-10-07 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estudiante',
        ),
    ]
