# Generated by Django 4.1 on 2022-10-12 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPage', '0002_delete_estudiante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='fecha',
            field=models.DateField(),
        ),
    ]
