# Generated by Django 4.1 on 2022-10-19 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPage', '0004_alter_blog_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='imagen',
        ),
    ]
