# Generated by Django 4.1 on 2022-10-20 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPage', '0005_remove_blog_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='fecha',
        ),
    ]
