# Generated by Django 4.1 on 2022-10-12 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='password',
            new_name='curso',
        ),
    ]
